# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/Sinhika/ashenwheat/issues" #optional
license="LGPL v3.0" #mandatory

[[mods]] #mandatory

modId="ashenwheat" #mandatory
version="${file.jarVersion}" #mandatory
displayName="akkamaddi's Ashenwheat" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Sinhika/ashenwheat/1.16/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/akkamaddis-ashenwheat" #optional
logoFile="ashwheatsheaf.png" #optional
credits="Thanks to akkamaddi for creating the original mod and to Sinhika for porting and maintaining it." #optional
authors="akkamaddi, Sinhika" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
a small farming mod, adding four utility crops: Ashenwheat (a fuel, and can make charcoal), Ossidroot (can make Bonemeal), Thundergrass (can make gunpowder), and Scintillawheat (can make Glowstone Dust).

Additional Credits: none yet.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.ashenwheat]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[36.1.0,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.ashenwheat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,]"
    ordering="NONE"
    side="BOTH"
