# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/Sinhika/ashenwheat/issues" #optional

[[mods]] #mandatory

modId="${mod_id}"
version="${version}"
displayName="${mod_name}"

updateJSONURL="https://raw.githubusercontent.com/Sinhika/ashenwheat/1.19/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/akkamaddis-ashenwheat" #optional
logoFile="ashwheatsheaf.png" #optional
credits="Thanks to akkamaddi for creating the original Ashenwheat mod, to Wuppy29 for creating the original PeacefulPack mod and to Sinhika for porting and maintaining it."
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="simplecorelib"
    mandatory=true
    versionRange="${simplecore_range}"
    ordering="NONE"
    side="BOTH"
